### ISSUE TITLE
How do I use sails-ioredis with a cluster (as opposed to sentinels)

### ISSUE THREAD

**Issue by kpturner** [Salakar/sails-ioredis#1]
How can I use a cluster as defined here: http://redis.io/topics/cluster-tutorial
Is this possible - presumably it must be but is there any documentation for a recommended way to configure the adaptor?

**Comment by Salakar** [comment]
Normally you'd just use cluster config from https://github.com/luin/ioredis#cluster but looks like I've not handled that, i'll make a PR to fix this.

**Comment by Salakar** [comment]
@kpturner done, can you give v0.2.0 a go - just provide an array of `hosts` in the config and it'll switch to cluster mode. See the config example in read me.

**Comment by kpturner** [comment]
Gr8 - thanks

**Comment by Salakar** [comment]
@kpturner did you get a chance to give this a go?

**Comment by kpturner** [comment]
Not yet I'm afraid - rather sidetracked ATM

**Comment by Salakar** [comment]
Ok, will leave this open till then. 👍

**Comment by kpturner** [comment]
You can close if you wish and we can look at it later

**Comment by Salakar** [comment]
Ok, create another PR if you run into any issues, thanks!
